### ISSUE TITLE
kotsadm-rqlite-db DB export fails due to credentials not being available

### ISSUE THREAD

**Issue by CpuID** [replicatedhq/troubleshoot-specs#82]
Seems the RQLITE_PASSWORD env var isn't available to the `kotsadm-rqlite` pod? But it's on the `kotsadm` pod. We need to adjust [the spec](https://github.com/replicatedhq/troubleshoot-specs/blob/main/in-cluster/default.yaml#L51-L61) to make that password available to the collector.

STR:

- install a Replicated KOTS app on a throwaway VM (eg. using kURL)
- ensure kotsadm is running with rqlite, example:

```
# kubectl get po | grep kotsadm
kotsadm-546dd567fc-bf7pn              1/1     Running   0          31m
kotsadm-rqlite-0                      1/1     Running   0          31m
kurl-proxy-kotsadm-7d565684d5-qn8sx   1/1     Running   0          31m
```

- run the below:

```
kubectl support-bundle https://raw.githubusercontent.com/replicatedhq/troubleshoot-specs/main/in-cluster/default.yaml`
tar xzvf support-bundle-*.tar.gz
cat support-bundle-*/kots/admin_console/default/kotsadm-rqlite-0/kotsadm-rqlite-db-*
[
  "command terminated with exit code 1"
]
wget: server returned error: HTTP/1.1 401 Unauthorized
```

Password is stored in this K8s secret:

```
export RQLITE_PASSWORD=$(kubectl get secret kotsadm-rqlite -o jsonpath='{.data.password}' | base64 -d)
echo $RQLITE_PASSWORD
<redacted>
```

Confirmed this works manually, by using it in an rqlite pod shell:

```
kubectl exec -it kotsadm-rqlite-0 -- /bin/sh
/ $ export RQLITE_PASSWORD=<password-from-above> # so it's available in the rqlite pod shell
/ $ wget -qO- kotsadm:${RQLITE_PASSWORD}@localhost:4001/db/backup?fmt=sql
PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
...
...
COMMIT;
```

**Comment by banjoh** [comment]
Perhaps we should collect the DB dump in the `kotsadm` pod instead of trying to get the env var available in the rqlite pod.

**Comment by banjoh** [comment]
We no longer collect KOTS DB in support bundles
